# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name : env
        env:
          VITE_FIREBASE_API_KEY: ${{secrets.VITE_FIREBASE_API_KEY}}
          VITE_FIREBASE_A_AUTHDOMAIN: ${{secrets.VITE_FIREBASE_A_AUTHDOMAIN}}
          VITE_FIREBASE_A_PROJECT_ID: ${{secrets.VITE_FIREBASE_A_PROJECT_ID}}
          VITE_FIREBASE_A_STORAGE_BUCKET: ${{secrets.VITE_FIREBASE_A_STORAGE_BUCKET}}
          VITE_FIREBASE_A_MESSAGING_SENDER_ID: ${{secrets.VITE_FIREBASE_A_MESSAGING_SENDER_ID}}
          VITE_FIREBASE_A_APP_ID: ${{secrets.VITE_FIREBASE_A_APP_ID}}
          VITE_FIREBASE_A_MEASUREMENT_ID: ${{secrets.VITE_FIREBASE_A_MEASUREMENT_ID}}
      - run: npm ci
      - run: npm test


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
